// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for **STAGING** environment.
///
/// Firebase Project: common-stag (616861138934)
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: StagingFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5SsoyINbJTBCCYPWtwke1VoQzwps__M',
    appId: '1:616861138934:web:2680c6ed7b1ea8b8d2d1d7',
    messagingSenderId: '616861138934',
    projectId: 'common-stag',
    authDomain: 'common-stag.firebaseapp.com',
    storageBucket: 'common-stag.firebasestorage.app',
    measurementId: 'G-JX4PQ5W4ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_u9q46Z3zQHNFmZLuwhiAOyWZMqotlU',
    appId: '1:616861138934:android:fa6289969dad4284d2d1d7',
    messagingSenderId: '616861138934',
    projectId: 'common-stag',
    storageBucket: 'common-stag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwtRIlixznqTvFyjLZgAEIrW3durIcvg',
    appId: '1:616861138934:ios:efbec74f31b43f9fd2d1d7',
    messagingSenderId: '616861138934',
    projectId: 'common-stag',
    storageBucket: 'common-stag.firebasestorage.app',
    iosBundleId: 'com.oxii.chat',
  );
}