// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for **PRODUCTION** environment.
///
/// Firebase Project: common-18e05 (159636416445)
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProductionFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_btYA6SUBWd0C1fa8bD1kEo2lbQgEN8M',
    appId: '1:159636416445:web:7d685acba80633532c94d4',
    messagingSenderId: '159636416445',
    projectId: 'common-18e05',
    authDomain: 'common-18e05.firebaseapp.com',
    storageBucket: 'common-18e05.firebasestorage.app',
    measurementId: 'G-E0KWEEHYHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5s_EoyiExDIA7QiXLI8_rYkCZ4HFVKZ4',
    appId: '1:159636416445:android:ab0c406e42e583e62c94d4',
    messagingSenderId: '159636416445',
    projectId: 'common-18e05',
    storageBucket: 'common-18e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfAPnRiPilpioD7jMuncX780W2JzDKe0',
    appId: '1:159636416445:ios:79b7effc0d4b095f2c94d4',
    messagingSenderId: '159636416445',
    projectId: 'common-18e05',
    storageBucket: 'common-18e05.firebasestorage.app',
    iosBundleId: 'com.oxii.chat',
  );
}
