// GENERATED CODE - DO NOT MODIFY BY HAND
// This is a placeholder file for Isar v4.0.0-dev.14 schema generation

part of 'chat_message_isar_model.dart';

// Placeholder schema - will be generated by Isar v4
const ChatMessageIsarModelSchema = null;

// Placeholder collection accessor - will be generated by Isar v4
extension ChatMessageIsarModelCollection on Isar {
  // Collection accessor will be generated here
}
