export const serviceAPI = {
    getListUserMange: 'user/list?s={s}&index={index}&size={size}&role={role}&organization={organization}',
    auth: {
        login: 'cms/user/login',
        logout: 'cms/user/logout',
        forgotPassword: 'cms/user/forgot-password',
        changePassword: 'cms/user/change-password',
        skipChangePassword: 'cms/user/skip-changing-password',
        resetPassword: 'cms/user/reset-password',
        checkToken: 'cms/user/forgot-password-token?token={token}',
        loginByPhone: 'app/user/signin',
        loginRole: 'karofi/app/user/roleSignin',
        userInfo: 'app/user/detail'
    },
    role: {
        list: 'cms/role/list',
        detail: 'cms/role/detail/{roleId}',
        edit: 'cms/role/edit',
        create: 'cms/role/create',
        delete: 'cms/role/delete/{roleId}',
        deleteCache: 'cms/role/deleteCacheRole',
        business: {
            list: 'cms/role/business/list'
        }
    },
    resource_list: 'cms/resource/list',
    country_list: 'karofi/app/address/country/list',
    province_list: 'karofi/app/address/province/list?countryId={countryId}',
    career_list: 'karofi/cms/career/list',
    permission_list: 'cms/permission/list',
    group: {
        list: 'cms/group/list?name={name}&page={page}&size={size}',
        create: 'cms/group/create',
        edit: 'cms/group/edit/{groupId}',
        delete: 'cms/group/delete/{groupId}',
        uploadImage: 'cms/group/upload-img/{groupId}'
    },
    property: {
        list: 'cms/device/property/list?page={page}&size={size}&name={name}',
        delete: 'cms/device/property/delete/{id}',
        create: 'cms/device/property/create',
        edit: 'cms/device/property/edit/{id}',
        detail: 'cms/device/property/detail/{id}'
    },
    user: {
        adminList: 'cms/user/list-admin',
        createAdmin: 'cms/user/create-admin',
        editAdmin: 'cms/user/edit-admin',
        delete: 'cms/user/delete-admin/{id}',
        customerList: 'cms/user/list-customer',
        activeCustomer: 'cms/user/active-customer/{customerId}',
        adminInfo: 'cms/user/admin-info',
        detail: 'cms/user/detail/{userId}',
        profile: 'cms/user/profile-detail',
        editProfile: 'cms/user/edit-profile',
        upload: 'cms/user/upFile',
        exportCtv: 'cms/collaborate/ctv/export?fromDate={fromDate}&toDate={toDate}',
        exportCtv2: 'cms/collaborate/ctv/export2',
        exportShop: 'cms/collaborate/shop/export?fromDate={fromDate}&toDate={toDate}',
        exportShop2: 'cms/collaborate/shop/export2',
        exportShopRelation: 'cms/organization/shop/export',
        exportShopByRegion: 'cms/collaborate/shop/export2',
        exportNpp: 'cms/collaborate/distributor/export?fromDate={fromDate}&toDate={toDate}',
        exportNpp2: 'cms/collaborate/distributor/export2',
        exportSale: 'cms/collaborate/sale/export',
        exportSale2: 'cms/collaborate/sale/export2',
        exportWarranties: 'karofi/cms/warranty/ctv/export?fromDate={fromDate}&toDate={toDate}',
        exportOwnerWarranties: 'karofi/cms/warranty/owner/export?fromDate={fromDate}&toDate={toDate}',
        exportProductRequest: 'karofi/cms/product/export-product-import2',
        exportWarehouseReceipt: 'karofi/cms/product/export-warehouse-receipt?fromDate={fromDate}&toDate={toDate}',
        exportExhibition: 'karofi/cms/user/export-exhibition2',
        exportRevenue: 'karofi/cms/product/export-revenue-estimate',
        exportRouteRegister: 'karofi/cms/user/export-route-register',
        exportComplaint: 'karofi/cms/user/export-complaint',
        exportCheckIn: 'karofi/cms/user/export-check-in',
        exportPotentialShop: 'karofi/cms/user/export-potential-shop',
        exportDailyReport: 'karofi/cms/user/export-daily-report',
        exportOrder: 'karofi/cms/order/export-order2',
        exportAddressZone: 'karofi/cms/address-zone/export',
        updateProductImports: 'karofi/cms/product/update-product-import',
        updateKHBHResults: 'karofi/cms/warranty/ctv/import-result',
        updateExhibitions: 'karofi/cms/user/update-exhibition',
        updateSaleStatuses: 'karofi/cms/user/update-sale-status',
        updateShopStatuses: 'karofi/cms/user/update-shop-status',
        updateDistributorStatuses: 'karofi/cms/user/update-distributor-status',
        updateCheckIns: 'karofi/cms/user/update-check-in',
        updateOrders: 'karofi/cms/order/update-order',
        updateSaleCareers: 'karofi/cms/address-zone/import-sale-career',
        sapOrderReport: 'karofi/cms/product/excel-sap-order',
        exportProductIncomeReport: 'karofi/cms/product/export-product-income',
        exportInventoryFromSale: 'karofi/cms/product/excel-warehouse-stats',
        listExhibition: 'karofi/cms/user/list-exhibition',
    },
    warehouse: {
        list: 'karofi/cms/user/list-warehouse',
        checkSerials: 'karofi/cms/factory/check-serials',
        checkActionSerials: 'karofi/cms/factory/check-action-serials',
        factoryImport: 'karofi/cms/factory/factory-import',
        selfImport: 'karofi/cms/factory/self-import',
        selfExport: 'karofi/cms/factory/self-export',
        listReceipt: 'karofi/cms/factory/list-receipt',
        excelReceipt: 'karofi/cms/factory/excel-receipt/{receiptId}',
        listDistributor: 'karofi/cms/warehouse/list-distributor?page={page}&size={size}&keyword={keyword}',
        listCompany: 'karofi/cms/warehouse/list-company?page={page}&size={size}&keyword={keyword}',
        importBlacklist: 'karofi/cms/factory/factory-import-blacklist',
        exportBlacklist: 'karofi/cms/factory/factory-export-blacklist',
        exportInventory: 'karofi/cms/inventory/export',
        exportInventoryDetail: 'karofi/cms/inventory/export-detail',
        importInventory: 'karofi/cms/factory/admin-import',
        distributorList: 'karofi/cms/warehouse/list-distributor',
        companyList: 'karofi/cms/warehouse/list-company',
        importCore: 'karofi/cms/factory/admin-import',
        transferCore: 'karofi/cms/factory/admin-transfer',
        productCore: 'karofi/cms/product-type/no-stamp-list?page={page}&size={size}&keyword={keyword}',
        transferByCode: 'karofi/cms/factory/admin-transfer-by-code',
        shopList: '/karofi/cms/warehouse/list-shop?page={page}&size={size}&keyword={keyword}'
    },
    device: {
        list: 'cms/device/list',
        delete: 'cms/device/delete/{deviceId}',
        create: 'cms/device/create',
        detail: 'cms/device/detail/{deviceId}',
        edit: 'cms/device/edit',
        listByCustomer: 'cms/device/list-by-customer?customerId={customerId}&page={page}&size={size}',
        addSerial: 'cms/device/add-seri',
        deviceType: {
            list: 'cms/device/device-type/list?page={page}&size={size}&name={name}',
            delete: 'cms/device/device-type/delete/{id}',
            create: 'cms/device/device-type/create',
            detail: 'cms/device/device-type/detail/{id}',
            upload: 'cms/device/device-type/upload-image/{id}',
            edit: 'cms/device/device-type/edit/{id}',
            listWithProperty: 'cms/device/device-type/list-with-properties?page={page}&size={size}'
        },
        protocol: {
            list: 'cms/device/protocol/list'
        },
        deleteSeriNumber: 'cms/device/remove-of-customer',
    },
    banner: {
        list: 'cms/banner/list?page={page}&size={size}&description={description}&orderDisplay={orderDisplay}&status={status}',
        activeBanner: 'cms/banner/active/{bannerId}',
        delete: 'cms/banner/delete/{bannerId}',
        create: 'cms/banner/create',
        detail: 'cms/banner/detail/{bannerId}',
        edit: 'cms/banner/edit/{bannerId}',
        upload: 'cms/banner/upload-img/{bannerId}'
    },
    news: {
        list: 'karofi/cms/news/list?page={page}&size={size}&keyword={keyword}&status={status}',
        delete: 'karofi/cms/news/delete/{newsId}',
        create: 'karofi/cms/news/create',
        detail: 'karofi/cms/news/detail/{newsId}',
        edit: 'karofi/cms/news/edit/{newsId}',
        upload: 'karofi/cms/news/upload-image/{newsId}'
    },
    region: {
        list: 'karofi/cms/region/list?page={page}&size={size}&keyword={keyword}',
        getList: 'karofi/cms/region/list',
        provinceList: 'karofi/cms/province/list?countryId={countryId}',
        delete: 'karofi/cms/region/delete/{regionId}',
        create: 'karofi/cms/region/create',
        set: 'karofi/cms/region/set',
        edit: 'karofi/cms/region/edit/{regionId}',
        provinces: 'karofi/cms/province/list',
        districts: 'karofi/app/address/district/list',
        wards: 'karofi/app/address/ward/list',
        addressZones: 'karofi/address-zone/tree/list?countryId={countryId}',
        assignOrganization: 'karofi/cms/region/add-organizations',
        assignRegionForSale: 'karofi/cms/region/set-sales',
        businessGroupList: 'karofi/cms/business-group/list',
        businessGroupCreate: 'karofi/cms/business-group/create',
        businessGroupUpdate: 'karofi/cms/business-group/edit',
        businessGroupDelete: 'karofi/cms/business-group/delete',
        assignBusinessGroupForSale: 'karofi/cms/business-group/set-sales',
        assignBusinessGroupForShop: 'karofi/cms/business-group/set-shops',
        assignBusinessGroupForDis: 'karofi/cms/business-group/set-distributors',
        channelList: 'karofi/cms/channel/list',
        channelCreate: 'karofi/cms/channel/create',
        channelUpdate: 'karofi/cms/channel/edit',
        channelDelete: 'karofi/cms/channel/delete',
    },
    promotion: {
        listProduct: 'karofi/cms/product-type/list?page={page}&size={size}&keyword={keyword}',
        listProductStampType: 'karofi/cms/product-type/list?page={page}&size={size}&keyword={keyword}&stampType={stampType}',
        listWarehouseProduct: 'karofi/cms/warehouse/product-type/list?page={page}&size={size}&keyword={keyword}',
        listTag: '/karofi/cms/promotion-tag/list',
        list: 'karofi/cms/promotion/list?page={page}&size={size}&keyword={keyword}&status={status}&type={type}',
        listCategory: 'karofi/cms/product-category/list',
        orderSetting: 'karofi/cms/product-category/order-setting',
        delete: 'karofi/cms/promotion/delete/{promotionId}',
        create: 'karofi/cms/promotion/create',
        add: 'karofi/cms/promotion/add',
        detail: 'karofi/cms/promotion/detail/{promotionId}',
        edit: 'karofi/cms/promotion/edit/{promotionId}',
        upload: 'karofi/cms/promotion/upload-image/{stt}/{promotionId}',
        uploadThumbnail: 'karofi/cms/promotion/upload-thumbnail/{promotionId}',
        createUpload: 'karofi/cms/promotion/upload-img',
        excelProductTypes: 'karofi/cms/product/export-product-types',
        updateProductTypes: 'karofi/cms/product/import-product-types'
    },
    order: {
        list: 'karofi/cms/order/list-order',
        edit: 'karofi/cms/order/update-distributor-order/{orderId}', //Tam
        sapCreate: 'karofi/cms/order/create',
        sapEdit: 'karofi/cms/order/update/{orderId}',
        listDistributor: 'karofi/cms/user/list-distributor?page={page}&size={size}&keyword={keyword}',
        listDistributionChannel: 'karofi/cms/sap-distribution-channel/list',
        listConditionType: 'karofi/cms/sap-condition-type/list',
        listCurrency: 'karofi/cms/sap-currency/list',
        listItemCategory: 'karofi/cms/sap-item-category/list',
        listPaymentTerm: 'karofi/cms/sap-payment-term/list',
        listPriceList: 'karofi/cms/sap-price-list/list',
        listPlant: 'karofi/cms/sap-plant/list',
        exportExcelOrder: 'karofi/cms/order/export-excel-order'
    },
    voucher: {
        list: 'karofi/cms/voucher/list?page={page}&size={size}&keyword={keyword}&status={status}&type={type}',
        delete: 'karofi/cms/voucher/delete/{voucherId}',
        create: 'karofi/cms/voucher/create',
        detail: 'karofi/cms/voucher/detail/{voucherId}',
        edit: 'karofi/cms/voucher/edit/{voucherId}',
        upload: 'karofi/cms/voucher/upload-image/{stt}/{voucherId}',
        uploadThumbnail: 'karofi/cms/voucher/upload-thumbnail/{voucherId}'
    },
    model: {
        list: 'cms/device/model/list?page={page}&size={size}&name={name}&displayDesktop={displayDesktop}&theme={theme}',
        delete: 'cms/device/model/delete/{id}',
        create: 'cms/device/model/create',
        detail: 'cms/device/model/detail/{id}',
        edit: 'cms/device/model/edit/{id}',
        upload: 'cms/device/model/upload-image/{id}'
    },
    supplier: {
        list: 'cms/supplier/list?name={name}&page={page}&size={size}'
    },
    notification: {
        list: 'cms/notification/list?page={page}&size={size}&title={title}&type={type}&startDate={startDate}&endDate={endDate}&location={location}&status={status}',
        create: 'cms/notification/create',
        createLoyaltyPoint: 'cms/notification/loyalty/create/bulk',
        createBulk: 'cms/notification/create/bulk',
        upload: 'cms/notification/upload-img/{id}',
        activeNotification: 'cms/notification/active/{id}',
    },
    dashboard: {
        device: 'cms/dashboard/device',
        customer: 'cms/dashboard/customer',
        firmware: 'cms/dashboard/firmware?deviceTypeId={deviceTypeId}',
        deviceType: 'cms/dashboard/device-type/list'
    },
    warranty: {
        listRequest: 'cms/warranty/listWarrantyReq?userId={userId}&page={page}&size={size}',
        listWarranty: 'cms/warranty/listWarranties?userId={userId}&page={page}&size={size}'
    },
    sensor: {
        listSensor: 'cms/sensor/listSensor/{deviceId}/{propertyId}?page={page}&size={size}&startDate={startDate}&endDate={endDate}&propertyRangeId={propertyRangeId}',
        listStatus: 'cms/sensor/listStatus/{propertyId}'
    },
    search: {
        listCollaborator: 'karofi/cms/user/list-all-collaborator?page={page}&size={size}&keyword={keyword}',
        listShop: 'karofi/cms/user/list-all-shop?page={page}&size={size}&keyword={keyword}',
        listDistributor: 'karofi/cms/user/list-all-distributor?page={page}&size={size}&keyword={keyword}'
    },
    pgSaleOut: {
        distributor: {
            list: 'karofi/cms/user/pg-distributor/list',
            create: 'karofi/cms/user/pg-distributor/create',
            update: 'karofi/cms/user/pg-distributor/edit',
            bulkCreate: 'karofi/cms/user/pg-distributor/bulk-create',
        },
        store: {
            list: 'karofi/cms/user/pg-shop/list',
            create: 'karofi/cms/user/pg-shop/create',
            update: 'karofi/cms/user/pg-shop/edit',
            bulkCreate: 'karofi/cms/user/pg-shop/bulk-create',
        },
        promotionGirl: {
            list: 'karofi/cms/user/pg-saleout/list',
            create: 'karofi/cms/user/pg-saleout/create',
            update: 'karofi/cms/user/pg-saleout/edit',
            registerImport: 'karofi/cms/user/pg-saleout/register',
        },
        exhibition: {
            list: 'karofi/cms/user/pg-exhibition/list',
            update: 'karofi/cms/user/pg-exhibition/edit',
        },
        checkIn: {
            list: 'karofi/cms/user/pg-checkin/list',
        },
        feature: {
            list: 'karofi/cms/pgsale/interest-feature/list',
            bulkCreate: 'karofi/cms/pgsale/interest-feature/bulk-create',
            create: 'karofi/cms/pgsale/interest-feature/create',
            edit: 'karofi/cms/pgsale/interest-feature/edit',
        },
        reason: {
            list: 'karofi/cms/pgsale/purchase-reason/list',
            bulkCreate: 'karofi/cms/pgsale/purchase-reason/bulk-create',
            create: 'karofi/cms/pgsale/purchase-reason/create',
            edit: 'karofi/cms/pgsale/purchase-reason/edit',
        },
        ageRange: {
            list: 'karofi/cms/pgsale/age-range/list',
            bulkCreate: 'karofi/cms/pgsale/age-range/bulk-create',
            create: 'karofi/cms/pgsale/age-range/create',
            edit: 'karofi/cms/pgsale/age-range/edit',
        },
        target: {
            list: 'karofi/cms/pgsale/target/list',
            bulkCreate: 'karofi/cms/pgsale/target/bulk-create',
            save: 'karofi/cms/pgsale/target/set',
        },
        saleOrder: {
            list: 'karofi/cms/pgsale/sale-orders',
            update: 'karofi/cms/pgsale/sale-order/edit',
        },
        GTPromotionGirl: {
            listShop: 'karofi/cms/user/list-all-shop',
            list: 'karofi/cms/user/pg-sale-gt/list',
            create: 'karofi/cms/user/pg-sale-gt/create',
            update: 'karofi/cms/user/pg-sale-gt/edit',
            assignShopForPG: 'karofi/cms/pgsale/gt-assign-organization',
        },
        device: {
            MTDeviceList: 'karofi/cms/org/list-pgsale-mt-device',
            GTDeviceList: 'karofi/cms/org/list-pgsale-gt-device',
            approve: 'karofi/cms/org/approve-pgdevice',
        }
    },
    manufacture: {
        stampLineList: 'karofi/cms/factory/stamp-line-list',
        stampGenerate: 'karofi/cms/factory/stamp-generate',
        stampApprove: 'karofi/cms/factory/stamp-approve',
        stampCancel: 'karofi/cms/factory/stamp-cancel',
        productionOrder: 'karofi/cms/factory/production-order',
        pendingPOList: 'karofi/cms/factory/pending-PO-list',
        POApprove: 'karofi/cms/factory/PO-approve',
        POReject: 'karofi/cms/factory/PO-reject',
        stampReplace: 'karofi/cms/factory/stamp-replace',
        stampByNoRange: 'karofi/cms/factory/stamp-by-no-range',
        POList: 'karofi/cms/factory/PO-list',
        POUpdate: 'karofi/cms/factory/production-order',
        createDevice: 'cms/fromKshop/device/create',
    },
    qc: {
        employeeList: 'karofi/cms/user/qc/list',
        updateEmployeeStatus: 'karofi/cms/user/update-qc-status',
        standardList: 'karofi/cms/factory/standard-list',
        standardCreate: 'karofi/cms/factory/quality-standard',
        standardCreateByCode: 'karofi/cms/factory/quality-standard/create',
        standardUpdate: 'karofi/cms/factory/quality-standard',
        standardUpdateByCode: 'karofi/cms/factory/quality-standard/update',
        standardDelete: 'karofi/cms/factory/quality-standard',
        lines: 'karofi/cms/factory/production-lines',
        lineCreate: 'karofi/cms/factory/production-line',
        lineUpdate: 'karofi/cms/factory/production-line',
        errors: 'karofi/cms/factory/production-errors',
        errorUpdate: 'karofi/cms/factory/production-error',
        errorCreate: 'karofi/cms/factory/production-error',
        errorTypes: 'karofi/cms/factory/error-types',
        errorTypeUpdate: 'karofi/cms/factory/error-type',
        errorTypeCreate: 'karofi/cms/factory/error-type',
        errorCategories: 'karofi/cms/factory/error-categories',
        errorCategoryCreate: 'karofi/cms/factory/error-category',
        errorCategoryUpdate: 'karofi/cms/factory/error-category',
        errorParts: 'karofi/cms/factory/error-parts',
        errorPartUpdate: 'karofi/cms/factory/error-part',
        errorPartCreate: 'karofi/cms/factory/error-part',
        components: 'karofi/cms/factory/components',
        componentUpdate: 'karofi/cms/factory/component',
        componentCreate: 'karofi/cms/factory/component',
        componentDelete: 'karofi/cms/factory/component',
    },
    userManagement: {
        ranks: 'karofi/cms/org/list-org-rank',
        banks: 'karofi/app/user/bank/list',
        shops: 'karofi/cms/org/list-all-shop',
        editShop: 'karofi/cms/org/edit-shop',
        distributors: 'karofi/cms/org/list-all-distributor',
        editDistributor: 'karofi/cms/org/edit-distributor',
        sales: 'karofi/cms/org/list-all-sale',
        positions: 'karofi/cms/user/job-position/list',
        editCollaborator: 'karofi/cms/org/edit-sale',
        setRoute: 'karofi/cms/org/set-routes',
        targets: 'karofi/cms/org/target/list',
        editTarget: 'karofi/cms/org/target/set',
        importTarget: 'karofi/cms/org/target/bulk-create',
        warranty: 'karofi/cms/warranty/search',
        warrantyUpdate: 'karofi/cms/warranty/update',
    },
    productManagement: {
        list: 'karofi/cms/product-type/list',
        stampList: 'karofi/cms/product-type/stampable-list',
        noStampList: 'karofi/cms/product-type/no-stamp-list',
        createProductVersion: 'karofi/cms/product-type/version',
        importProductVersion: 'karofi/cms/product-type/bulk-version',
        updateSerialVersion: 'karofi/cms/stamp/update-product-version',
        checkComponent: 'karofi/cms/stamp/check-component',
        categories: 'karofi/cms/product-category/list',
        updateProductType: 'karofi/cms/product-type/edit',
        createProductType: 'karofi/cms/product-type/create',
    },
    quickSight: {
        cmsDashboardList: 'karofi/cms/quick-sight/dashboard/list',
        cmsEmbedURL: 'karofi/cms/quick-sight/dashboard/getEmbedUrl',
        appDashboardList: 'karofi/app/quick-sight/dashboard/list',
        appEmbedURL: 'karofi/app/quick-sight/dashboard/getEmbedUrl',
    },
    telesale: {
        telesaleAccounts: 'karofi/cms/telesale/list',
        createTelesaleAccount: 'karofi/cms/telesale/create',
        updateTelesaleAccount: 'karofi/cms/telesale/edit',
        listRelationShop: 'karofi/app/user/list-relation-shop',
        shopDetail: 'karofi/app/org/shop-detail/{shopId}',
        shopHistoryOrder: 'karofi/app/org/shop-orders/{shopId}?page={page}&size={size}',
        listDistributor: 'karofi/app/telesale/list-distributor',
        listPromotions: 'karofi/app/telesale/list-promotion',
        listValidVoucher: 'karofi/app/telesale/list-valid-voucher',
        createOrder: 'karofi/app/telesale/create-order',
        updateOrder: 'karofi/app/telesale/update-order',
    },
    crm: {
        assignComponentForProduct: 'karofi/cms/product-type/bulk-crm-version'
    }
};
