import { BaseError } from '../modules/core/core.error'

export const CRMError = {
  AddressZoneNotExisted: new BaseError('CRM.AddressZoneNotExisted', 'Địa chính không tồn tại'),
  BusinessRoleNotExist: new BaseError('CRM.BusinessRoleNotExist', 'Vai trò không tồn tại'),
  EmptyExcelFile: new BaseError('CRM.EmptyExcelFile', 'Không có dữ liệu trong tập tin excel'),
  WrongFormatExcelFile: new BaseError('CRM.WrongFormatExcelFile', 'Định dạng dữ liệu trong tập tin excel không đúng'),
  SaleNotExisted: new BaseError('CRM.SaleNotExisted', 'Không tìm thấy nhân viên kinh doanh'),
  PhoneIsRequired: new BaseError('CRM.PhoneIsRequired', 'Số điện thoại là bắt buộc'),
  CrmUserNotExist: new BaseError('CRM.UserNotExist', 'Người dùng không tồn tại'),
  FileNotExist: new BaseError('CRM.FileNotExist', 'Tệp tin không tồn tại'),
  CrmCustomerNotExit: new BaseError('CRM.CustomerNotExit', 'Khách hàng không tồn tại'),
  CrmCustomerExited: new BaseError('CRM.CustomerExisted', 'Khách hàng đã tồn tại'),
  CrmCustomerNotOwnThiPhone: new BaseError('CRM.CustomerNotOwnThiPhone', 'Bạn không sở hữu số điện thoại này'),
  CrmUserWithPhoneExisted: new BaseError('CRM.UserWithPhoneExisted', 'Người dùng với số điện thoại đã tồn tại'),
  CrmUserWithUsernameExisted: new BaseError('CRM.UserWithUsernameExisted', 'Người dùng với email đã tồn tại'),
  CrmUserWithEmailExisted: new BaseError('CRM.UserWithEmailExisted', 'Người dùng với tên đăng nhập đã tồn tại'),
  CrmUserGroupNotExist: new BaseError('CRM.UserGroupNotExist', 'Nhóm người dùng không tồn tại'),
  CrmUserInactive: new BaseError('CRM.UserInactive', 'Tài khoản chưa được kích hoạt'),
  CreatePermissionActionHasUnexpectedError: new BaseError('CRM.CreatePermissionActionHasUnexpectedError', 'Khởi tạo hành động gặp lỗi không xác định'),
  RemovePermissionActionHasUnexpectedError: new BaseError('CRM.RemovePermissionActionHasUnexpectedError', 'Xoá hành động gặp lỗi không xác định'),
  CreatePermissionPolicyHasUnexpectedError: new BaseError('CRM.CreatePermissionPolicyHasUnexpectedError', 'Khởi tạo quyền gặp lỗi không xác định'),
  RemovePermissionPolicyHasUnexpectedError: new BaseError('CRM.RemovePermissionPolicyHasUnexpectedError', 'Xoá quyền gặp lỗi không xác định'),
  CreatePermissionRoleHasUnexpectedError: new BaseError('CRM.CreatePermissionRoleHasUnexpectedError', 'Khởi tạo nhóm quyền gặp lỗi không xác định'),
  RemovePermissionRoleHasUnexpectedError: new BaseError('CRM.RemovePermissionRoleHasUnexpectedError', 'Xoá nhóm quyền gặp lỗi không xác định'),
  UnsupportedOrganization: new BaseError('CRM.UnsupportedOrganization', 'Hệ thống không hỗ trợ tổ chức đã chọn'),
  DataIsNotBelongToOrganization: new BaseError('CRM.DataIsNotBelongToOrganization', 'Dữ liệu không thuộc tổ chức'),
  LeadSourceExisted: new BaseError('CRM.LeadSourceExisted', 'Nguồn dữ liệu đã tồn tại'),
  LeadSourceNotExist: new BaseError('CRM.LeadSourceNotExist', 'Nguồn dữ liệu không tồn tại'),
  LeadExisted: new BaseError('CRM.LeadExisted', 'Lead đã tồn tại'),
  LeadNotExisted: new BaseError('CRM.LeadNotExisted', 'Lead không tồn tại'),
  LeadResultExisted: new BaseError('CRM.LeadResultExisted', 'Loại kết quả của Lead đã tồn tại'),
  LeadResultNotExist: new BaseError('CRM.LeadResultNotExist', 'Loại kết quả của Lead không tồn tại'),
  OrderTypeExisted: new BaseError('CRM.OrderTypeExisted', 'Loại đơn hàng đã tồn tại'),
  OrderTypeNotExist: new BaseError('CRM.OrderTypeNotExist', 'Loại đơn hàng không tồn tại'),
  OrderTypeParentNotExist: new BaseError('CRM.OrderTypeParentNotExist', 'Loại đơn hàng cha không tồn tại'),
  DepartmentNotExisted: new BaseError('CRM.DepartmentNotExisted', 'Phòng ban không tồn tại'),
  DepartmentExisted: new BaseError('CRM.DepartmentExisted', 'Phòng ban đã tồn tại'),
  CrmUserStatusNotExist: new BaseError('CRM.CrmUserStatusNotExist', 'Trạng thái người dùng không tồn tại'),
  CrmUserStatusExisted: new BaseError('CRM.CrmUserStatusExisted', 'Trạng thái người dùng đã tồn tại'),
  CrmSaleNotExist: new BaseError('CRM.CrmSaleNotExist', 'Nhân viên kinh doanh không tồn tại'),
  CrmCollaboratorNotExist: new BaseError('CRM.CrmCollaboratorNotExist', 'Cộng tác viên không tồn tại'),
  LeadKtcReasonExisted: new BaseError('CRM.LeadKtcReasonExisted', 'Kết quả liên hệ đã tồn tại'),
  LeadKtcReasonNotExist: new BaseError('CRM.LeadKtcReasonNotExist', 'Kết quả liên hệ không tồn tại'),
  DealKtcReasonExisted: new BaseError('CRM.DealKtcReasonExisted', 'Lý do chốt đơn KTC đã tồn tại'),
  DealKtcReasonNotExist: new BaseError('CRM.DealKtcReasonNotExist', 'Lý do chốt đơn KTC không tồn tại'),
  DealMarketingExisted: new BaseError('CRM.DealMarketingExisted', 'Chương trình Marketing đã tồn tại'),
  DealMarketingNotExist: new BaseError('CRM.DealMarketingNotExist', 'Chương trình Marketing không tồn tại'),
  DealInstallmentExisted: new BaseError('CRM.DealInstallmentExisted', 'Chương trình cho thuê / trả góp đã tồn tại'),
  DealInstallmentNotExist: new BaseError('CRM.DealInstallmentNotExist', 'Chương trình cho thuê / trả góp không tồn tại'),
  DealExisted: new BaseError('CRM.DealExisted', 'Deal đã tồn tại'),
  DealNotExist: new BaseError('CRM.DealNotExist', 'Deal không tồn tại'),
  ProductNotExist: new BaseError('CRM.ProductNotExist', 'Sản phẩm không tồn tại'),
  ProductTypeNotExist: new BaseError('CRM.ProductTypeNotExist', 'Loại sản phẩm không tồn tại'),
  ProductCountNotExist: new BaseError('CRM.ProductCountNotExist', 'Số lượng sản phẩm không tồn tại'),
  DealResultExisted: new BaseError('CRM.DealResultExisted', 'Kết quả chốt đơn đã tồn tại'),
  DealResultNotExist: new BaseError('CRM.DealResultNotExist', 'Kết quả chốt đơn không tồn tại'),
  DeliveryShippingVendorExisted: new BaseError('CRM.DeliveryShippingVendorExisted', 'Đơn vị vận chuyển đã tồn tại'),
  DeliveryShippingVendorNotExist: new BaseError('CRM.DeliveryShippingVendorNotExist', 'Đơn vị vận chuyển không tồn tại'),
  DeliveryShippingStatusExisted: new BaseError('CRM.DeliveryShippingStatusExisted', 'Trạng thái giao hàng đã tồn tại'),
  DeliveryShippingStatusNotExist: new BaseError('CRM.DeliveryShippingStatusNotExist', 'Trạng thái giao hàng không tồn tại'),
  DeliveryShippingMethodExisted: new BaseError('CRM.DeliveryShippingMethodExisted', 'Phương thức giao hàng đã tồn tại'),
  DeliveryShippingMethodNotExist: new BaseError('CRM.DeliveryShippingMethodNotExist', 'Phương thức giao hàng không tồn tại'),
  DeliveryExisted: new BaseError('CRM.DeliveryExisted', 'Đơn giao hàng đã tồn tại'),
  DeliveryNotExist: new BaseError('CRM.DeliveryNotExist', 'Đơn giao hàng không tồn tại'),
  WarehouseExisted: new BaseError('CRM.WarehouseExisted', 'Kho hàng đã tồn tại'),
  WarehouseNotExist: new BaseError('CRM.WarehouseNotExist', 'Kho hàng không tồn tại'),
  ScheduleWorkingShiftExisted: new BaseError('CRM.ScheduleWorkingShiftExisted', 'Ca làm việc đã tồn tại'),
  ScheduleWorkingShiftNotExist: new BaseError('CRM.ScheduleWorkingShiftNotExist', 'Ca làm việc không tồn tại'),
  InstallationResultExisted: new BaseError('CRM.InstallationResultExisted', 'Kết quả lắp đặt đã tồn tại'),
  InstallationResultNotExist: new BaseError('CRM.InstallationResultNotExist', 'Kết quả lắp đặt không tồn tại'),
  InstallationKtcReasonExisted: new BaseError('CRM.InstallationKtcReasonExisted', 'Kết quả liên hệ KTC đã tồn tại'),
  InstallationKtcReasonNotExist: new BaseError('CRM.InstallationKtcReasonNotExist', 'Kết quả liên hệ KTC không tồn tại'),
  ScheduleExisted: new BaseError('CRM.ScheduleExisted', 'Lịch làm việc đã tồn tại'),
  ScheduleNotExist: new BaseError('CRM.ScheduleNotExist', 'Lịch làm việc không tồn tại'),
  InstallationExisted: new BaseError('CRM.InstallationExisted', 'Đơn lắp đặt đã tồn tại'),
  InstallationNotExist: new BaseError('CRM.InstallationNotExist', 'Đơn lắp đặt không tồn tại'),
  CrmTechnicianNotExist: new BaseError('CRM.CrmTechnicianNotExist', 'Kỹ thuật viên không tồn tại'),
  InstallationSupportResultExisted: new BaseError('CRM.InstallationSupportResultExisted', 'Kết quả hỗ trợ sơ bộ đã tồn tại'),
  InstallationSupportResultNotExist: new BaseError('CRM.InstallationSupportResultNotExist', 'Kết quả hỗ trợ sơ bộ không tồn tại'),
  DealPromotionExisted: new BaseError('CRM.DealPromotionExisted', 'Chương trình cho thuê / trả góp đã tồn tại'),
  DealPromotionNotExist: new BaseError('CRM.DealPromotionNotExist', 'Chương trình cho thuê / trả góp không tồn tại'),
  ProductBrandExisted: new BaseError('CRM.ProductBrandExisted', 'Thương hiệu sản phẩm đã tồn tại'),
  ProductBrandNotExist: new BaseError('CRM.ProductBrandNotExist', 'Thương hiệu sản phẩm không tồn tại'),
  ProductCategoryExisted: new BaseError('CRM.ProductCategoryExisted', 'Nhóm sản phẩm đã tồn tại'),
  ProductCategoryNotExist: new BaseError('CRM.ProductCategoryNotExist', 'Nhóm sản phẩm không tồn tại'),
  ProductTypeExisted: new BaseError('CRM.ProductTypeExisted', 'Loại sản phẩm đã tồn tại'),
  ProductExisted: new BaseError('CRM.ProductExisted', 'Sản phẩm đã tồn tại'),
  PolicyServiceExisted: new BaseError('CRM.PolicyServiceExisted', 'Dịch vụ đã tồn tại'),
  PolicyServiceNotExist: new BaseError('CRM.PolicyServiceNotExist', 'Dịch vụ không tồn tại'),
  PolicyActionExisted: new BaseError('CRM.PolicyActionExisted', 'Chức năng của dịch vụ đã tồn tại'),
  PolicyActionNotExist: new BaseError('CRM.PolicyActionNotExist', 'Chức năng của dịch vụ không tồn tại'),
  WarehouseTypeExisted: new BaseError('CRM.WarehouseTypeExisted', 'Loại kho hàng đã tồn tại'),
  WarehouseTypeNotExist: new BaseError('CRM.WarehouseTypeNotExist', 'Loại kho hàng không tồn tại'),
  ImportWarehouseNotExist: new BaseError('CRM.ImportWarehouseNotExist', 'Không tìm thấy kho hàng nhập'),
  ExportWarehouseNotExist: new BaseError('CRM.ExportWarehouseNotExist', 'Không tìm thấy kho hàng xuất'),
  ProductNotExistInExportWarehouse: new BaseError('CRM.ProductNotExistInExportWarehouse', 'Không tìm thấy sản phẩm trong kho hàng xuất'),
  InventoryNotEnough: new BaseError('CRM.InventoryNotEnough', 'Số lượng sản phẩm không đủ'),
  NoProductSelected: new BaseError('CRM.NoProductSelected', 'Chưa chọn sản phẩm nào'),
  DeliveryIsNotOwner: new BaseError('CRM.DeliveryIsNotOwner', 'Kho hàng không sở hữu đơn giao đã chọn'),
  ScheduleIsOverlap: new BaseError('CRM.ScheduleIsOverlap', 'Lịch làm việc bị trùng'),
  PolicyExisted: new BaseError('CRM.PolicyExisted', 'Quyền đã tồn tại'),
  PolicyNotExist: new BaseError('CRM.PolicyNotExist', 'Quyền không tồn tại'),
  OptionNotExist: new BaseError('CRM.OptionNotExist', 'Lựa chọn không tồn tại'),
  OptionExisted: new BaseError('CRM.OptionExisted', 'Lựa chọn đã tồn tại'),
  OptionParentNotExist: new BaseError('CRM.OptionParentNotExist', 'Lựa chọn cha không tồn tại'),
  OptionChildExisted: new BaseError('CRM.OptionChildExisted', 'Lựa chọn con tồn tại'),
  InstallationAtNotFound: new BaseError('CRM.InstallationAtNotFound', 'Thời gian lắp đặt không tồn tại'),
  IncidentResultNotExist: new BaseError('CRM.IncidentResultNotExist', 'Kết quả liên hệ không tồn tại'),
  IncidentRequestGroupNotExist: new BaseError('CRM.IncidentRequestGroupNotExist', 'Nhóm yêu cầu không tồn tại'),
  IncidentMarketNotExist: new BaseError('CRM.IncidentMarketNotExist', 'Mã siêu thị không tồn tại'),
  IncidentSourceNotExist: new BaseError('CRM.IncidentSourceNotExist', 'Nguồn không tồn tại'),
  IncidentPartnerNotExist: new BaseError('CRM.IncidentPartnerNotExist', 'Đối tác không tồn tại'),
  IncidentTypeNotExist: new BaseError('CRM.IncidentTypeNotExist', 'Loại sự vụ không tồn tại'),
  IncidentNotExist: new BaseError('CRM.IncidentNotExist', 'Sự cố không tồn tại'),
  OptionFinalNotExist: new BaseError('CRM.OptionFinalNotExist', 'Lựa chọn cuối cùng không tồn tại'),
  OptionIsFixed: new BaseError('CRM.OptionIsFixed', 'Trạng thái hiện tại không được phép thay đổi'),
  IncidentIsNotExist: new BaseError('CRM.IncidentIsNotExist', 'Sự vụ không tồn tại'),
  TechnicianIsNotExist: new BaseError('CRM.TechnicianIsNotExist', 'Không tìm thấy thông tin kỹ thuật viên'),
  IncidentAlreadyHasTechnician: new BaseError('CRM.IncidentAlreadyHasTechnician', 'Sự vụ đã được giao cho kỹ thuật viên'),
  IncidentDontHasTechnician: new BaseError('CRM.IncidentDontHasTechnician', 'Sự vụ chưa được giao cho kỹ thuật viên nào'),
  ProductComponentNotExist: new BaseError('CRM.ProductComponentNotExist', 'Linh kiện sản phẩm không tồn tại'),
  ProductComponentExisted: new BaseError('CRM.ProductComponentExisted', 'Linh kiện sản phẩm đã tồn tại'),
  ResultIsNotEditable: new BaseError('CRM.ResultIsNotEditable', 'Không thể chỉnh do đã ở trạng thái cuối cùng'),
  DataNotOwneredByYou: new BaseError('CRM.DataNotOwneredByYou', 'Bạn không sở hữu dữ liệu này'),
  WarrantyTypeNotExist: new BaseError('CRM.WarrantyTypeNotExist', 'Hình thức bảo hành không tồn tại'),
  WarrantyNotExist: new BaseError('CRM.WarrantyNotExist', 'Phiếu bảo hành không tồn tại'),
  SystemProgressNotExist: new BaseError('CRM.SystemProgressNotExist', 'Trạng thái không tồn tại'),
  IncidentPriorityNotExist: new BaseError('CRM.IncidentPriorityNotExist', 'Độ ưu tiên sự vụ không tồn tại'),
  IncidentRequestTypeNotExist: new BaseError('CRM.IncidentRequestTypeNotExist', 'Loại yêu cầu không tồn tại'),
  IncidentInternalReasonNotExist: new BaseError('CRM.IncidentInternalReasonNotExist', 'Nguyên nhân không tồn tại'),
  IncidentInternalDepartmentNotExist: new BaseError('CRM.IncidentInternalDepartmentNotExist', 'Phòng ban không tồn tại'),
  IncidentAlreadyCheckedIn: new BaseError('CRM.IncidentAlreadyCheckedIn', 'Sự vụ đã được check in'),
  IncidentAlreadyClosed: new BaseError('CRM.IncidentAlreadyClosed', 'Sự vụ đã được đóng'),
  IncidentIsNotEditable: new BaseError('CRM.IncidentIsNotEditable', 'Bạn không thể sửa thông tin khi sự vụ đang được sử lý bởi kỹ thuật viên'),
  ComplainHandlerNotFound: new BaseError('CRM.ComplainHandlerNotFound', 'Không tìm thấy người xử lý khiếu nại'),
  IncidentTroubleGroupNotExist: new BaseError('CRM.IncidentTroubleGroupNotExist', 'Nhóm lỗi không tồn tại'),
  IncidentTroubleReasonNotExist: new BaseError('CRM.IncidentTroubleReasonNotExist', 'Nguyên nhân lỗi không tồn tại'),
  IncidentTroubleAnalysisNotExist: new BaseError('CRM.IncidentTroubleAnalysisNotExist', 'Đánh giá lỗi không tồn tại'),
  IncidentCancelReasonNotExist: new BaseError('CRM.IncidentCancelReasonNotExist', 'Lý do hủy không tồn tại'),
  IncidentActionIsNotAllow: new BaseError('CRM.IncidentActionIsNotAllow', 'Thao tác không cho phép với sự vụ này'),
  CrmComplainHandlerNotExist: new BaseError('CRM.CrmComplainHandlerNotExist', 'Chuyên viên giải quyết khiếu nại không tồn tại'),
  ComplainNotExist: new BaseError('CRM.ComplainNotExist', 'Khiếu nại không tồn tại'),
  ComplainVendorAlreadyAdded: new BaseError('CRM.ComplainVendorAlreadyAdded', 'Bộ phận xử lý khiếu nại đã tồn tại'),
  ComplainVendorNotExist: new BaseError('CRM.ComplainVendorNotExist', 'Bộ phận xử lý khiếu nại không tồn tại'),
  ComplainNotEnoughParam: new BaseError('CRM.ComplainNotEnoughParam', 'Khiếu nại chưa được điền đầy đủ thông tin'),
  InvalidDataInput: new BaseError('CRM.InvalidDataInput', 'Dữ liệu đầu vào không đúng'),
  NotificationNotExist: new BaseError('CRM.NotificationNotExist', 'Thông báo không tồn tại'),
  YouDontHasPermissionToAccessThisData: new BaseError('CRM.YouDontHasPermissionToAccessThisData', 'Bạn không có quyền truy cập vào dữ liệu này'),
  TechniciainNotBelongToYourGroup: new BaseError('CRM.TechniciainNotBelongToYourGroup', 'Kỹ thuật viên không thuộc nhóm của bạn'),
  ComplainActionIsNotAllow: new BaseError('CRM.ComplainActionIsNotAllow', 'Thao tác không cho phép với khiếu nại này'),
  ProductTypeIgnoredManualUpdate: new BaseError('CRM.ProductTypeIgnoredManualUpdate', 'Loại sản phẩm (nhãn KRF) không được phép cập nhật thủ công'),
  GroupAlreadyHasLeader: new BaseError('CRM.GroupAlreadyHasLeader', 'Nhóm kỹ thuật viên đã có trưởng nhóm'),
  WarrantyProgressNotExist: new BaseError('CRM.WarrantyProgressNotExist', 'Tiến độ bảo hành không tồn tại'),
  SLAZoneExisted: new BaseError('CRM.SLAZoneExisted', 'Khu vực SLA đã tồn tại'),
  SLAZoneNotExist: new BaseError('CRM.SLAZoneNotExist', 'Khu vực SLA không tồn tại'),
  SLAGroupExisted: new BaseError('CRM.SLAGroupExisted', 'Nhóm SLA đã tồn tại'),
  SLAGroupNotExist: new BaseError('CRM.SLAGroupNotExist', 'Nhóm SLA không tồn tại'),
  SLATimeExisted: new BaseError('CRM.SLATimeExisted', 'Thời gian SLA đã tồn tại'),
  SLATimeNotExist: new BaseError('CRM.SLATimeNotExist', 'Thời gian SLA không tồn tại'),
  SLAAddressExisted: new BaseError('CRM.SLAAddressExisted', 'Khu vực địa chỉ SLA đã tồn tại'),
  SLAAddressNotExist: new BaseError('CRM.SLAAddressNotExist', 'Khu vực địa chỉ SLA không tồn tại'),
  SLATroubleExisted: new BaseError('CRM.SLATroubleExisted', 'Lỗi SLA đã tồn tại'),
  SLATroubleNotExist: new BaseError('CRM.SLATroubleNotExist', 'Lỗi SLA không tồn tại'),
  TechnicianGroupIsRequiredForTechnicianRole: new BaseError('CRM.TechnicianGroupIsRequiredForTechnicianRole', 'Chưa chọn nhóm kỹ thuật viên cho vai trò kỹ thuật viên'),
  TechnicianGroupIsRequiredForLeaderRole: new BaseError('CRM.TechnicianGroupIsRequiredForLeaderRole', 'Chưa chọn nhóm kỹ thuật viên cho vai trò trưởng nhóm'),
  TechnicianGroupIsNotBelongToYou: new BaseError('CRM.TechnicianGroupIsNotBelongToYou', 'Bạn không phải trưởng nhóm kỹ thuật viên đã chọn'),
  IncidentExpireReasonNotExist: new BaseError('CRM.IncidentExpireReasonNotExist', 'Lý do quá hạn không tồn tại'),
  LogisticProviderNotExist: new BaseError('CRM.LogisticProviderNotExist', 'Dịch vụ vận chuyển không tồn tại'),
  LogisticTypeNotExist: new BaseError('CRM.LogisticTypeNotExist', 'Loại hình vận chuyển không tồn tại'),
  LogisticProgressNotExist: new BaseError('CRM.LogisticProgressNotExist', 'Tiến độ vận chuyển không tồn tại'),
  LogisticProgressChangeNotAllow: new BaseError('CRM.LogisticProgressChangeNotAllow', 'Không cho phép đồng thời thay đổi hình thức vận chuyển và tiến độ vận chuyển'),
  WarehouseWarrantyNotExist: new BaseError('CRM.WarehouseWarrantyNotExist', 'Kho hàng bảo hành không tồn tại'),
  ChangeWarrantyProgressNotAllow: new BaseError('CRM.ChangeWarrantyProgressNotAllow', 'Tiến độ bảo hành không được phép thay đổi'),
  OrderExisted: new BaseError('CRM.OrderExisted', 'Đơn hàng đã tồn tại'),
  OrderNotExist: new BaseError('CRM.OrderNotExist', 'Đơn hàng không tồn tại'),
  OrderProgressNotExist: new BaseError('CRM.OrderProgressNotExist', 'Tiến độ đơn hàng không tồn tại'),
  OrderProposalTypeNotExist: new BaseError('CRM.OrderProposalTypeNotExist', 'Loại đơn hàng không tồn tại'),
  OrderPaymentStatusNotExist: new BaseError('CRM.OrderPaymentStatusNotExist', 'Tính trạng thanh toán không tồn tại'),
  OrderInvoiceTypeNotExist: new BaseError('CRM.OrderInvoiceTypeNotExist', 'Loại hóa đơn không tồn tại'),
  ForgotPasswordRequestNotExist: new BaseError('CRM.ForgotPasswordRequestNotExist', 'Yêu cầu đặt lại mật khẩu không tồn tại'),
  ForgotPasswordRequestActionIsNotAllow: new BaseError('CRM.ForgotPasswordRequestActionIsNotAllow', 'Thao tác không cho phép với yêu cầu đặt lại mật khẩu này'),
  TechnicianLeaderRoleIsRequired: new BaseError('CRM.TechnicianLeaderRoleIsRequired', 'Tính năng yêu cầu vai trò trưởng nhóm'),
  CredentialIsrequired: new BaseError('CRM.CredentialIsrequired', 'Thiếu thông tin xác thực'),
  SocialNetworkNotExisted: new BaseError('CRM.SocialNetworkNotExisted', 'Mạng xã hội không tồn tại'),
}
