import { BaseError } from "src/modules/core/core.error";

export const OfficeErrorMessage = {
    WrongFormatField: (fieldName: string) => `Vui lòng nhập đúng định dạng trường ${fieldName}`,
    FieldMustIn: (fieldName: string, list: string) => `Giá trị trường ${fieldName} phải thuộc danh sách sau: ${list}`,
    CannotUpdateField: (fieldName: string) => `Không được cập nhật giá trị ${fieldName}`,
    MaxLengthField: (fieldName: string, length: number | string) => `Độ dài trường ${fieldName} không vượt quá ${length.toString()} ký tự`,
    MinLengthField: (fieldName: string, length: number | string) => `Độ dài trường ${fieldName} không ít hơn ${length.toString()} ký tự`,
    NotFound: 'Thông tin không tồn tại',
    PropertyNameNotExist: 'Thuộc tính không tồn tại',
    NotAllow: 'Bạn không có quyền thực hiện điều này',
    DataFound: 'Thông tin không được phép tồn tại',
    TooManyRequests: 'Quá nhiều yêu cầu, vui lòng chờ và thử lại sau',
    WrongDataInput: 'Thông tin nhập vào không chính xác',
    NotInThePastDate: 'Không được là thời gian trong quá khứ',
    ListHaveSameValue: 'Danh sách có phần tử trùng nhau',
    DataNotChange: 'Dữ liệu không có gì thay đổi',
    AdminNeedLinkUser: "Bạn cần gán tài khoản user của mình để có thể thực hiện thao tác này",
    CannotChangeUser: "Không được phép thay đổi nhân viên",
    ShiftAtLeastADay: 'Ca làm việc phải áp dụng ít nhất 1 ngày trong tuần',
    ShiftLunchShoutBetweenWorkDay: 'Giá trị giờ nghỉ giữa ca phải nằm trong thời gian ca làm việc',
    ShiftValueFromZeroToOne: 'Giá trị trừ ngày công chưa đúng',
    RequiredField: 'Vui lòng nhập đầy đủ trường bắt buộc',
    StatusWrongType: 'Vui lòng nhập trạng thái là Active hoặc Inactive',
    DBRequestError: 'Lỗi thao tác',
    UserPaycheckExistInDate: 'Đã tồn tại phiếu lương của nhân viên trong tháng',
    UserPaycheckNotExist: 'Phiếu lương không tồn tại',
    UserPaycheckCannotEditUser: 'Không được phép thay đổi nhân viên của phiếu lương',
    UserPaycheckCannotEditPayroll: 'Không được phép thay đổi bảng lương của phiếu lương',
    OfficeTitleNotExisted: 'Chức vụ không tồn tại',
    OfficeLeaderNotExisted: 'Mã quản lý trực tiếp không tồn tại trên hệ thống',
    OfficeUserResignedTypeError: 'Giá trị thôi việc là "Có" hoặc "Không"',
    IpNotInWhiteList: 'Ip của bạn không được phép checkin',
    CheckInRequiredLocationPermission: 'Cần quyền truy cập vị trí của thiết bị để sử dụng tính năng này',
    DepartmentNotExist: 'Phòng ban không tồn tại',
    ChatWrongSender: 'Bạn không phải là người tạo tin nhắn',
    ChatMessageNeedReceiverOrConversation: 'Người nhận hoặc cuộc trò chuyện là bắt buộc',
    ChatMessageNotFound: 'Không tìm thấy tin nhắn',
    ChatMessageActNotAllow: 'Không thể thực hiện hành động này với tin nhắn',
    ChatUserNotInConversation: 'Bạn không thuộc cuộc trò chuyện này',
    ChatObjectRequiredConversation: 'Thông tin cuộc trò chuyện là bắt buộc cho việc tạo message',
    ChatConversationNotExist: 'Cuộc trò chuyện không tồn tại',
    ChatNotAdmin: 'Bạn không phải là admin',
    ChatCanNotRemoveSelf: 'Không thể xóa chính mình khỏi cuộc trò chuyện',
    ChatCanNotLeaveDirectConversation: 'Bạn không thể rời cuộc trò chuyện trực tiếp',
    DepartmentNotHaveManager: 'Không thấy thông tin người quản lý phòng ban',
    YouIsManagerOfDepartment: 'Bạn chính là người quản lý phòng ban này',
    RTCErrorCannotMakeCallToYourself: 'Không thể thực hiện cuộc gọi cho chính mình',
    RTCErrorRecipientInforNotFound: 'Thông tin người nhận không tồn tại',
    RTCErrorYouAreOnAnotherCall: 'Bạn đang trong một cuộc gọi khác',
    RTCErrorCallInfoNotFound: 'Không tìm thấy thông tin cuộc gọi',
    RTCErrorTheCallHasEnded: 'Cuộc gọi đã kết thúc',
    RTCErrorUnableToConnectToUser: 'Không thể kết nối tới người dùng',
    RTCErrorTheCallIsNotSharedWithYou: 'Cuộc gọi không được chia sẻ với bạn',
    UserNotHavePayroll: 'Nhân viên không có bảng lương này',
    WrongDatePeriod: 'Ngày bắt đầu và kết thúc không hợp lệ',
    WrongEndDatePeriod: 'Ngày kết thúc phải lớn hơn ngày bắt đầu',
    TaskNotExist: 'Thông tin task không tồn tại',
    TaskNotAllowEditDoneTask: 'Tác vụ không được phép với task ở trạng thái “Hoàn thành”',
    TaskNotAllowEditCancelTask: 'Tác vụ không được phép với task ở trạng thái “Hủy bỏ”',
    TaskUserNotHavePermission: 'Bạn không có quyền thao tác task này',
    TaskCommentNotOwnUser: 'Bình luận này không phải của bạn',
    MeetingRoomNotFound: 'Không tìm thấy phòng họp!',
    MeetingRoomExistedName: 'Tên phòng họp đã tồn tại trên hệ thống',
    BookingMeetingRoomNotFound: 'Không tìm thấy thông tin đặt phòng họp!',
    BookingRoomCanNotChange: 'Lịch họp này không được phép cập nhật/xóa',
    BookingRoomNotApprovalCanNotChange: 'Lịch họp chưa được duyệt không được phép cập nhật',
    BookingRoomScheduleNotFound: 'Lịch họp không tồn tại',
    BookingRoomNotAvailable: 'Phòng họp không sẵn sàng trong khoảng thời gian đã chọn',
    BookingRoomHostNotFound: 'Người chủ trì không tồn tại',
    BookingRoomParticipantNotFound: 'Người tham gia không tồn tại',
    BookingRoomNotInThePast: 'Thời gian bắt đầu cuộc họp không là thời điểm trong quá khứ',
    OfficeCarNotExisted: 'Thông tin xe không tồn tại',
    BookingCarScheduleNotFound: 'Lịch đặt xe không tồn tại',
    BookingCarNotAvailable: 'Xe không sẵn sàng trong khoảng thời gian đã chọn',
    BookingCarNotInThePast: 'Không thể đặt xe tại thời điểm trong quá khứ',
    BookingCarNotApprovalCanNotChange: 'Lịch đặt xe chưa được duyệt không được phép cập nhật',
    BookingCarCanNotChange: 'Lịch đặt xe này không được phép cập nhật/xóa',
    LogCommentRequiredData: 'Vui lòng nhập tin nhắn hoặc đính kèm',
    LogCommentAttachmentRequiredType: 'Hãy chọn loại đính kèm',
    ChatSearchMessageConversationRequiredPartner: "Thông tin người trò chuyện cùng là bắt buộc",
    ChatSearchMessageGroupRequiredInfo: "Thông tin nhóm là bắt buộc",
    UserNotExist: "Người dùng không tồn tại",
    OrgChartNotFound: "Không tìm thấy đơn vị cơ cấu tổ chức",
    OrgChartCodeIsExistNotFound: "Mã phòng ban đã tồn tại",
    OrgTitleNotFound: "Chức danh không tồn tại",
    UserWorkProfileNotFound: "Thông tin làm việc không tồn tại",
    UserWorkProfileMetadataWrongInput: "Nhập sai thông tin các trường yêu cầu dựa theo hình thức thay đổi",
    DoNotUpdateUserAtHere: "Không thực hiện cập nhật thông tin người dùng tại đây",
    CannotUpdateWorkProfileDataWhenUpdateUser: "Không được phép cập nhật thông tin quá trình làm việc tại đây",
    EmployeeCodeIsExisted: "Mã nhân viên đã tồn tại trên hệ thống",
    EmployeeCodeIsNotExisted: "Mã nhân viên không tồn tại trên hệ thống",
    WorkProfileInfoTypeError: 'Quyết đinh có giá trị là "Có" hoặc "Không"',
    WorkProfileInfoActionTypeCannotUpdate: 'Không được thay đổi loại của quá trình',
    OfficeLeaderUserNotExisted: 'Quản lý trực tiếp không tồn tại',
    ActiveDteOfUserWorkProfileMustUnique: 'Nhân viên đã có quá trình làm việc hiệu lực trong ngày này',
    WrongUserId: 'ID nhân viên không chính xác',
    CampaignNeedReceiver: "Thông tin nhận thông báo là bắt buộc",
    CampaignUserGetNotifyNotExist: "Người nhận thông báo không tồn tại",
    CampaignPersonalRequireReceiver: "Người nhận thông báo là bắt buộc trong trường hợp gửi cá nhân",
    ApprovalNotFound: "Không tìm thấy tờ trình phê duyệt",
    ApprovalNeedUsed: "Người hoặc phòng ban sử dụng là bắt buộc",
    AssetNotFound: "Tài sản không tồn tại",
    AssetDataNotSameOrg: "Các thông tin lựa chọn phải của chung 1 Tập đoàn",
    AssetOnlyOneManagementData: "Chỉ nhập một trong hai thông tin về quản lý",
    AssetOnlyOneAssignData: "Chỉ nhập một trong hai thông tin về sử dụng",
    CategoryAssetNotFound: "Danh mục tài sản không tồn tại",
    WarehouseAssetNotFound: "Kho lưu trữ không tồn tại",
    CheckInBeaconNotFound: "Mã bí mật không chính xác",
    CheckInNeedPlaceNotFound: "Vui lòng chọn địa điểm chấm công",
    AssetNotHaveQuantity: "Tài sản cập nhật là duy nhất, không có thông tin số lượng.",
    OrgChartEmployeeNotEmpty: "Đơn vị có nhân viên, không thực hiện được thao tác",
    ApprovalCanNotUpdate: "Phê duyệt không được phép cập nhật",
    ApprovalCanNotRemoveDefaultSubscriber: "Không thể xóa người nhận thông báo mặc định",
    FilterNameExist: "Tên danh mục đã tồn tại",
    FilterNotFound: "Danh mục không tồn tại",
    FilterUserApprovalNameExist: "Tên danh mục đã tồn tại",
    FilterUserApprovalNotFound: "Danh mục không tồn tại",
    CloneConfigNotFound: "Cấu hình nhân bản không tồn tại",
    CloneConfigByDateNeedEndOfSchedule: "Thời gian kết thúc lặp lại là bắt buộc",
    ApprovalFormNotFound: "Không tìm thấy mẫu tờ trình phê duyệt",
    ApprovalFormGroupNotExist: "Nhóm phê duyệt không tồn tại",
    ApprovalFormGroupNameExist: "Tên nhóm phê duyệt đã tồn tại",
    ApprovalFormGroupHaveFormCanNotRemove: "Không được xóa nhóm đang tồn tại mẫu phê duyệt",
    ApprovalForwardRequiredUser: "Người nhận chuyển tiếp là bắt buộc",
    DocumentFolderNeedDepartmentOrUser: "Thưc mục cần thuộc về ít nhất một phòng ban hoặc cá nhân",
    DocumentFolderNotFound: "Không tìm thấy thư mục tài liệu",
    DocumentWikiNotFound: "Không tìm thấy tài liệu",
    DocumentWikiNameExisted: "Tên tài liệu đã tồn tại trong thư mục",
    DocumentWikiCodeExisted: "Mã tài liệu đã tồn tại trong thư mục",
    DocumentWikiCanNotCreateNewVer: "Tài liệu hiện đang có phiên bản chờ phê duyệt, không thể tạo phiên bản mới",
    DocumentWikiCannotRemove: "Tài liệu không được phép xóa",
    NeedApproval: "Thông tin phê duyệt là bắt buộc",
    VersionWikiNotFound: "Không tìm thấy phiên bản tài liệu",
    VersionWikiUpdateNeedUpdateType: "Thông tin về loại cập nhật là bắt buộc",
    VersionWikiNotApprovalCannotRevert: "Không thể khôi phục phiên bản chưa được phê duyệt",
    CategoryWikiNotFound: "Loại tài liệu không tồn tại",
    CategoryWikiNameExist: "Tên loại tài liệu đã tồn tại",
    CategoryWikiHaveWikiCanNotRemove: "Không được xóa nhóm đang tồn tại mẫu tài liệu",
    DeviceNotApprovedThisAccount: "Thiết bị không được phê duyệt ở tài khoản này",
    DeviceHasApproved: "Thiết bị đăng ký đã được phê duyệt",
    NotFoundDevice: "Không tìm thấy thông tin đăng kí thiết bị",
    OrgChartNotAlowThisFeature: "Đăng kí thiết bị không phù hợp cho org chart này",
    TagDocumentNotFound: "Thẻ không tồn tại",
    TagDocumentNameExist: "Tên thẻ đã tồn tại",
    TagDocumentHaveWikiCanNotRemove: "Không được xóa thẻ đang được sử dụng",
    LearningProjectCodeExisted: "Mã khóa học đã tồn tại. Không thể tạo khóa học với mã này!",
    LearningProjectNameExisted: "Tên khóa học đã tồn tại. Không thể tạo khóa học với mã này!",
    LearningProjectNotFound: "Khóa học không tồn tại",
    LearningProjectHasStudent: "Khóa học đã cấp chứng chỉ hoặc có học viên tham gia. Không thể xóa",
    LearningProjectStatusCannotUpdate: "Không được cập nhật khóa học với trạng thái hiện tại",
    LearningProjectHaveActiveCourse: "Khóa học vẫn còn lớp đang hoạt động",
    LearningProjectStatusCannotHide: "Lớp học đã có sinh viên tham gia và trạng thái không phải là Kết thúc, không thể thực hiện thao tác này",
    LearningSkillNameExisted: "Tên kỹ năng đã tồn tại",
    LearningSkillNotFound: "Kỹ năng không tồn tại",
    LearningCertificateNameExisted: "Tên chứng chỉ đã tồn tại",
    LearningCertificateNotFound: "Chứng chỉ không tồn tại",
    LearningSectionNotFound: "Học phần không tồn tại",
    LearningLessonNotFound: "Bài giảng không tồn tại",
    LearningCourseNotFound: "Lớp học không tồn tại",
    LearningCourseClosed: "Lớp học đã kết thúc",
    LearningCourseCodeExisted: "Mã lớp học đã tồn tại. Không thể tạo lớp học với mã này",
    LearningCourseNameExisted: "Tên lớp học đã tồn tại. Không thể tạo lớp học với tên này",
    LearningSectionNameExisted: "Tên học phần đã tồn tại. Không thể tạo học phần với tên này",
    LearningLessonNameExisted: "Tên bài giảng đã tồn tại. Không thể tạo bài giảng với tên này",
    LearningAddressNotFound: "Vị trí lớp học không tồn tại",
    LearningAddressNameExisted: "Vị trí lớp học đã tồn tại",
}

export const OfficeError = {
    ActionNotAllowed: (message?: string) => message ?
        new BaseError('Office.ActionNotAllowed', message) :
        new BaseError('Office.ActionNotAllowed', 'Thao tác không cho phép'),
    WrongFormatField: (fieldName: string) => new BaseError('Office.WrongFormatField', OfficeErrorMessage.WrongFormatField(fieldName)),
    FieldMustIn: (fieldName: string, list: string) => new BaseError('Office.FieldMustIn', OfficeErrorMessage.FieldMustIn(fieldName, list)),
    CannotUpdateField: (fieldName: string) => new BaseError('Office.CannotUpdateField', OfficeErrorMessage.CannotUpdateField(fieldName)),
    MaxLengthField: (fieldName: string, length: number | string) => new BaseError('Office.MaxLengthField', OfficeErrorMessage.MaxLengthField(fieldName, length)),
    MinLengthField: (fieldName: string, length: number | string) => new BaseError('Office.MinLengthField', OfficeErrorMessage.MinLengthField(fieldName, length)),
    NotFound: new BaseError('Office.NotFound', OfficeErrorMessage.NotFound),
    PropertyNameNotExist: new BaseError('Office.PropertyNameNotExist', OfficeErrorMessage.PropertyNameNotExist),
    NotAllow: new BaseError('Office.NotAllow', OfficeErrorMessage.NotAllow),
    RequiredField: new BaseError('Office.RequiredField', OfficeErrorMessage.RequiredField),
    DataFound: new BaseError('Office.DataFound', OfficeErrorMessage.DataFound),
    TooManyRequests: new BaseError('Office.TooManyRequests', OfficeErrorMessage.TooManyRequests),
    NotInThePastDate: new BaseError('Office.NotInThePastDate', OfficeErrorMessage.NotInThePastDate),
    ListHaveSameValue: new BaseError('Office.ListHaveSameValue', OfficeErrorMessage.ListHaveSameValue),
    DataNotChange: new BaseError('Office.DataNotChange', OfficeErrorMessage.DataNotChange),
    AdminNeedLinkUser: new BaseError('Office.AdminNeedLinkUser', OfficeErrorMessage.AdminNeedLinkUser),
    CannotChangeUser: new BaseError('Office.CannotChangeUser', OfficeErrorMessage.CannotChangeUser),
    StatusWrongType: new BaseError('Office.StatusWrongType', OfficeErrorMessage.StatusWrongType),
    ProfileBlockNotExisted: new BaseError('Office.ProfileBlockNotExisted', 'Khối thông tin không tồn tại'),
    ProfileBlockIsExisted: new BaseError('Office.ProfileBlockIsExisted', 'Tên khối đã tồn tại'),
    ProfileBlockCodeIsExisted: new BaseError('Office.ProfileBlockIsExisted', 'Mã khối đã tồn tại'),
    ProfileFieldIsExisted: new BaseError('Office.ProfileFieldIsExisted', 'Tên trường đã tồn tại'),
    ProfileFieldCodeIsExisted: new BaseError('Office.ProfileFieldIsExisted', 'Mã trường đã tồn tại'),
    ProfileFieldNotExisted: new BaseError('Office.ProfileFieldNotExisted', 'Trường thông tin không tồn tại'),
    AddressZoneInvalid: new BaseError('Office.AddressZoneInvalid', 'Địa chỉ không hợp lệ'),
    BankNotExisted: new BaseError('Office.BankNotExisted', 'Ngân hàng không hợp lệ'),
    FileNotExisted: new BaseError('Office.FileNotExisted', 'Tệp tin không tồn tại'),
    BusinessRoleNotExist: new BaseError('Office.BusinessRoleNotExist', 'Vai trò không tồn tại'),
    BusinessRoleIsExist: new BaseError('Office.BusinessRoleIsExist', 'Vai trò đã tồn tại'),
    UserNotExist: new BaseError('Office.UserNotExist', OfficeErrorMessage.UserNotExist),
    UserWorkProfileNotFound: new BaseError('Office.UserWorkProfileNotFound', OfficeErrorMessage.UserWorkProfileNotFound),
    UserWorkProfileMetadataWrongInput: new BaseError('Office.UserWorkProfileMetadataWrongInput', OfficeErrorMessage.UserWorkProfileMetadataWrongInput),
    SysUserWithEmailExisted: new BaseError('Office.SysUserWithEmailExisted', 'Người dùng với email đã tồn tại'),
    SysUserNotExisted: new BaseError('Office.SysUserWithEmailExisted', 'Tài khoản không tồn tại'),
    SysUserWithCodeExisted: new BaseError('Office.SysUserWithEmailExisted', 'Người dùng với mã nhân viên đã tồn tại'),
    OfficeUserWithEmailNotExisted: new BaseError('Office.OfficeUserWithEmailNotExisted', 'Email nhân viên không tồn tại'),
    OfficeUserWithPhoneNotExisted: new BaseError('Office.OfficeUserWithPhoneNotExisted', 'SĐT nhân viên không tồn tại'),
    OfficeLeaderUserNotExisted: new BaseError('Office.OfficeLeaderUserNotExisted', OfficeErrorMessage.OfficeLeaderUserNotExisted),
    EmployeeCodeIsExisted: new BaseError('Office.EmployeeCodeIsExisted', OfficeErrorMessage.EmployeeCodeIsExisted),
    EmployeeCodeIsNotExisted: new BaseError('Office.EmployeeCodeIsNotExisted', OfficeErrorMessage.EmployeeCodeIsNotExisted),
    EmployeeCodeIsWrong: new BaseError('Office.EmployeeCodeIsWrong', 'Mã nhân viên có chiều dài 5 ký tự'),
    EmployeeCodeEditIsWrongFormat: new BaseError('Office.EmployeeCodeEditIsWrongFormat', 'Mã nhân viên sửa đổi không hợp lệ'),
    EmployeePhoneIsExisted: new BaseError('Office.EmployeePhoneIsExisted', 'Số điện thoại đã tồn tại trên hệ thống'),
    EmployeeNotFound: new BaseError('Office.EmployeeNotFound', 'Không tìm thấy nhân viên'),
    EmployeeHrCodeIsExisted: new BaseError('Office.EmployeeHrCodeIsExisted', 'Mã chấm công đã tồn tại trên hệ thống'),
    EmployeeIDCardIsExisted: new BaseError('Office.EmployeeIDCardIsExisted', 'CCCD/CMT đã tồn tại trên hệ thống'),
    EmployeeSocialInsuranceCodeIsExisted: new BaseError('Office.EmployeeSocialInsuranceCodeIsExisted', 'Mã BHXH đã tồn tại trên hệ thống'),
    EmployeeTaxCodeIsExisted: new BaseError('Office.EmployeeTaxCodeIsExisted', 'Mã số thuế đã tồn tại trên hệ thống'),
    OfficeTitleIsExisted: new BaseError('Office.OfficeTitleIsExisted', 'Chức vụ đã tồn tại'),
    OfficeTitleNotExisted: new BaseError('Office.OfficeTitleNotExisted', OfficeErrorMessage.OfficeTitleNotExisted),
    OfficeCarNotExisted: new BaseError('Office.OfficeCarNotExisted', OfficeErrorMessage.OfficeCarNotExisted),
    OfficeCarBookingScheduleNotExisted: new BaseError('Office.OfficeCarBookingScheduleNotExisted', 'Lịch đặt xe không tồn tại'),
    OrgChartNotFound: new BaseError('Office.OrgChartNotFound', OfficeErrorMessage.OrgChartNotFound),
    OrgChartCodeIsExistNotFound: new BaseError('Office.OrgChartCodeIsExistNotFound', OfficeErrorMessage.OrgChartCodeIsExistNotFound),
    OrgTitleNotFound: new BaseError('Office.OrgTitleNotFound', OfficeErrorMessage.OrgTitleNotFound),
    SysUserNotHavePermission: new BaseError('Office.SysUserNotHavePermission', 'Bạn không có quyền tìm kiếm tổ chức này'),
    OrgChartNameExisted: new BaseError('Office.OrgChartNameExisted', 'Tên đơn vị đã tồn tại trong tổ chức'),
    OrgChartParentInvalid: new BaseError('Office.OrgChartParentInvalid', 'Đơn vị cấp trên trực tiếp không hợp lệ'),
    OrgChartNotEmptyEmployee: new BaseError('Office.OrgChartNotEmptyEmployee', 'Chỉ xóa những đơn vị không có nhân viên nào'),
    OrgChartEmployeeNotEmpty: new BaseError('Office.OrgChartEmployeeNotEmpty', OfficeErrorMessage.OrgChartEmployeeNotEmpty),
    PhoneNumberInvalid: new BaseError('Office.PhoneNumberInvalid', 'Số điện thoại không đúng định dạng'),
    ApprovalFormIsExisted: new BaseError('Office.ApprovalFormIsExisted', 'Tên mẫu tờ trình phê duyệt đã tồn tại'),
    ApprovalFormTableFieldEmptyColumn: new BaseError('Office.ApprovalFormTableFieldEmptyColumn', 'Bảng dữ liệu trong mẫu tờ trình phê duyệt cần ít nhất 1 cột'),
    FormApproverNotFound: new BaseError('Office.FormApproverNotFound', 'Không tìm thấy người phê duyệt'),
    FormDepartmentNotFound: new BaseError('Office.FormDepartmentNotFound', 'Không tìm thấy bộ phận phê duyệt'),
    FormConsentByNotFound: new BaseError('Office.FormConsentByNotFound', 'Không tìm thấy người xác nhận'),
    ApprovalFormNotFound: new BaseError('Office.ApprovalFormNotFound', OfficeErrorMessage.ApprovalFormNotFound),
    DocumentFolderNotFound: new BaseError('Office.DocumentFolderNotFound', OfficeErrorMessage.DocumentFolderNotFound),
    DocumentFolderNeedDepartmentOrUser: new BaseError('Office.DocumentFolderNeedDepartmentOrUser', OfficeErrorMessage.DocumentFolderNeedDepartmentOrUser),
    DocumentFolderPermissionDenied: new BaseError('Office.DocumentFolderPermissionDenied', 'Không có quyền truy cập thư mục tài liệu'),
    DocumentFolderIsExisted: new BaseError('Office.DocumentFolderIsExisted', 'Tên thự mục đã tồn tại'),
    DocumentFolderParentInvalid: new BaseError('Office.DocumentFolderParentInvalid', 'Thư mục cha không hợp lệ'),
    DocumentFolderParentNotFound: new BaseError('Office.DocumentFolderParentNotFound', 'Không tìm thấy thư mục cha'),
    DocumentFileNotFound: new BaseError('Office.DocumentFileNotFound', 'Không tìm thấy tài liệu'),
    DocumentFileIsExisted: new BaseError('Office.DocumentFileIsExisted', 'Tên tài liệu đã tồn tại'),
    DocumentFilePermissionDenied: new BaseError('Office.DocumentFilePermissionDenied', 'Không có quyền truy cập tài liệu'),
    PublicIpIsExisted: new BaseError('Office.PublicIpIsExisted', 'IP Public đã tồn tại'),
    CheckInPlaceIsExisted: new BaseError('Office.CheckInPlaceIsExisted', 'Điểm check-in/checkout đã tồn tại'),
    CheckInPlaceNotFound: new BaseError('Office.CheckInPlaceNotFound', 'Không tìm thấy điểm check-in/checkout'),
    CheckInRecordNotFound: new BaseError('Office.CheckInRecordNotFound', 'Không tìm thấy thông tin check-in/checkout trên hệ thống'),
    IpNotInWhiteList: new BaseError('Office.IpNotInWhiteList', OfficeErrorMessage.IpNotInWhiteList),
    CheckInRequiredLocationPermission: new BaseError('Office.CheckInRequiredLocationPermission', OfficeErrorMessage.CheckInRequiredLocationPermission),
    AccountNotExisted: new BaseError('Office.AccountNotExisted', 'Người dùng không tồn tại'),
    EndTimeCannotLessThanStartTime: new BaseError('Office.EndTimeCannotLessThanStartTime', 'Thời gian kết thúc không được sớm hơn thời gian bắt đầu'),
    CarBookingScheduleOverlap: new BaseError('Office.CarBookingScheduleOverlap', 'Lịch đặt xe bị trùng'),
    InactivedAccount: new BaseError('Office.InactivedAccount', 'Người dùng đã bị vô hiệu hóa'),
    ApprovalStructureIsRequired: new BaseError('Office.ApprovalStructureIsRequired', 'Yêu cầu cấu trúc để khởi tạo phê duyệt'),
    ApprovalNotFound: new BaseError('Office.ApprovalNotFound', OfficeErrorMessage.ApprovalNotFound),
    ApprovalFieldIsRequired: new BaseError('Office.ApprovalFieldIsRequired', 'Trường thông tin bắt buộc nhập'),
    ApprovalFieldInvalid: new BaseError('Office.ApprovalFieldInvalid', 'Trường thông tin nhập không hợp lệ'),
    ApprovalNameIsRequired: new BaseError('Office.ApprovalNameIsRequired', 'Tên phê duyệt bắt buộc nhập'),
    MeetingRoomNotFound: new BaseError('Office.MeetingRoomNotFound', OfficeErrorMessage.MeetingRoomNotFound),
    MeetingRoomExistedName: new BaseError('Office.MeetingRoomExistedName', OfficeErrorMessage.MeetingRoomExistedName),
    BookingMeetingRoomNotFound: new BaseError('Office.BookingMeetingRoomNotFound', OfficeErrorMessage.BookingMeetingRoomNotFound),
    BookingRoomCanNotChange: new BaseError('Office.BookingRoomCanNotChange', OfficeErrorMessage.BookingRoomCanNotChange),
    BookingRoomNotApprovalCanNotChange: new BaseError('Office.BookingRoomNotApprovalCanNotChange', OfficeErrorMessage.BookingRoomNotApprovalCanNotChange),
    BookingRoomScheduleNotFound: new BaseError('Office.BookingRoomScheduleNotFound', OfficeErrorMessage.BookingRoomScheduleNotFound),
    BookingRoomNotAvailable: new BaseError('Office.BookingRoomNotAvailable', OfficeErrorMessage.BookingRoomNotAvailable),
    BookingRoomHostNotFound: new BaseError('Office.BookingRoomHostNotFound', OfficeErrorMessage.BookingRoomHostNotFound),
    BookingRoomParticipantNotFound: new BaseError('Office.BookingRoomParticipantNotFound', OfficeErrorMessage.BookingRoomParticipantNotFound),
    BookingRoomNotInThePast: new BaseError('Office.BookingRoomNotInThePast', OfficeErrorMessage.BookingRoomNotInThePast),
    BookingCarScheduleNotFound: new BaseError('Office.BookingCarScheduleNotFound', OfficeErrorMessage.BookingCarScheduleNotFound),
    BookingCarNotAvailable: new BaseError('Office.BookingCarNotAvailable', OfficeErrorMessage.BookingCarNotAvailable),
    BookingCarNotInThePast: new BaseError('Office.BookingCarNotInThePast', OfficeErrorMessage.BookingCarNotInThePast),
    BookingCarNotApprovalCanNotChange: new BaseError('Office.BookingCarNotApprovalCanNotChange', OfficeErrorMessage.BookingCarNotApprovalCanNotChange),
    BookingCarCanNotChange: new BaseError('Office.BookingCarCanNotChange', OfficeErrorMessage.BookingCarCanNotChange),
    BookingCarNotFound: new BaseError('Office.BookingCarNotFound', 'Không tìm thấy thông tin đặt xe!'),
    MeetingRoomNotAvailable: new BaseError('Office.MeetingRoomNotAvailable', 'Phòng họp không có sẵn!'),
    EmptyExcelFile: new BaseError('Office.EmptyExcelFile', 'File excel không có nội dung'),
    SerialAssetNotFound: new BaseError('Office.SerialAssetNotFound', 'Serial tài sản không tồn tại'),
    StampNFCuIdInvalid: new BaseError('Office.StampNFCuIdInvalid', 'Mã uID của thẻ NFC không hợp lệ'),
    StampNFCrollingCodeNotFound: new BaseError('Office.StampNFCrollingCodeNotFound', 'Mã rollingCode của thẻ NFC không tồn tại'),
    StampNFCuIdIsRequired: new BaseError('Office.StampNFCuIdIsRequired', 'Mã uID của thẻ NFC là bắt buộc'),
    UnrecognizedAssetSerials: new BaseError("Office.UnrecognizedAssetSerials", "Serial tài sản không xác định"),
    InfoFieldNotExisted: new BaseError('Office.InfoFieldNotExisted', 'Thông tin không tồn tại'),
    ShiftCodeExist: new BaseError('Office.ShiftCodeExist', 'Mã ca làm việc đã tồn tại trên hệ thống'),
    ShiftAtLeastADay: new BaseError('Office.ShiftAtLeastADay', OfficeErrorMessage.ShiftAtLeastADay),
    ShiftLunchShoutBetweenWorkDay: new BaseError('Office.ShiftLunchShoutBetweenWorkDay', OfficeErrorMessage.ShiftLunchShoutBetweenWorkDay),
    ShiftValueFromZeroToOne: new BaseError('Office.ShiftValueFromZeroToOne', OfficeErrorMessage.ShiftValueFromZeroToOne),
    NotificationPhonesIsRequired: new BaseError('Office.NotificationPhonesIsRequired', 'Số điện thoại bắt buộc nhập'),
    NotificationDepartmentsIsRequired: new BaseError('Office.NotificationDepartmentsIsRequired', 'Phòng ban bắt buộc nhập'),
    NotificationTitlesIsRequired: new BaseError('Office.NotificationTitlesIsRequired', 'Chức vụ bắt buộc nhập'),
    NotificationStartTimeIsRequired: new BaseError('Office.NotificationStartTimeIsRequired', 'Thời gian bắt buộc nhập'),
    NotificationStartAtIsRequired: new BaseError('Office.NotificationStartAtIsRequired', 'Ngày bắt đầu bắt buộc nhập'),
    NotificationEndAtIsRequired: new BaseError('Office.NotificationEndAtIsRequired', 'Ngày kết thúc bắt buộc nhập'),
    NotificationAtIsRequired: new BaseError('Office.NotificationAtIsRequired', 'Ngày gửi thông báo bắt buộc nhập'),
    NotificationCampaignNotFound: new BaseError('Office.NotificationCampaignNotFound', 'Không tìm thấy thông tin thông báo'),
    PayrollExist: new BaseError('Office.PayrollExist', 'Tên bảng lương đã tồn tại'),
    PayrollNotExist: new BaseError('Office.PayrollNotExist', 'Bảng lương không tồn tại'),
    UserNotHavePayroll: new BaseError('Office.UserNotHavePayroll', OfficeErrorMessage.UserNotHavePayroll),
    PayrollCodeExist: new BaseError('Office.PayrollCodeExist', 'Mã bảng lương đã tồn tại'),
    PayrollCodeNotExist: new BaseError('Office.PayrollCodeNotExist', 'Mã bảng lương không tồn tại trên hệ thống'),
    UserPaycheckExistInDate: new BaseError('Office.UserPaycheckExistInDate', OfficeErrorMessage.UserPaycheckExistInDate),
    UserPaycheckNotExist: new BaseError('Office.UserPaycheckNotExist', OfficeErrorMessage.UserPaycheckNotExist),
    UserPaycheckCannotEditUser: new BaseError('Office.UserPaycheckCannotEditUser', OfficeErrorMessage.UserPaycheckCannotEditUser),
    UserPaycheckCannotEditPayroll: new BaseError('Office.UserPaycheckCannotEditPayroll', OfficeErrorMessage.UserPaycheckCannotEditPayroll),
    OfficeUserResignedTypeError: new BaseError('Office.OfficeUserResignedTypeError', OfficeErrorMessage.OfficeUserResignedTypeError),
    DepartmentNotExist: new BaseError('Office.DepartmentNotExist', OfficeErrorMessage.DepartmentNotExist),
    DepartmentNotHaveManager: new BaseError('Office.DepartmentNotHaveManager', OfficeErrorMessage.DepartmentNotHaveManager),
    YouIsManagerOfDepartment: new BaseError('Office.YouIsManagerOfDepartment', OfficeErrorMessage.YouIsManagerOfDepartment),
    ChatWrongSender: new BaseError('Office.ChatWrongSender', OfficeErrorMessage.ChatWrongSender),
    ChatMessageNeedReceiverOrConversation: new BaseError('Office.ChatMessageNeedReceiverOrConversation', OfficeErrorMessage.ChatMessageNeedReceiverOrConversation),
    ChatMessageActNotAllow: new BaseError('Office.ChatMessageActNotAllow', OfficeErrorMessage.ChatMessageActNotAllow),
    ChatMessageNotFound: new BaseError('Office.ChatMessageNotFound', OfficeErrorMessage.ChatMessageNotFound),
    ChatUserNotInConversation: new BaseError('Office.ChatUserNotInConversation', OfficeErrorMessage.ChatUserNotInConversation),
    ChatObjectRequiredConversation: new BaseError('Office.ChatObjectRequiredConversation', OfficeErrorMessage.ChatObjectRequiredConversation),
    ChatConversationNotExist: new BaseError('Office.ChatConversationNotExist', OfficeErrorMessage.ChatConversationNotExist),
    ChatCanNotLeaveDirectConversation: new BaseError('Office.ChatCanNotLeaveDirectConversation', OfficeErrorMessage.ChatCanNotLeaveDirectConversation),
    ChatNotAdmin: new BaseError('Office.ChatNotAdmin', OfficeErrorMessage.ChatNotAdmin),
    ChatCanNotRemoveSelf: new BaseError('Office.ChatCanNotRemoveSelf', OfficeErrorMessage.ChatCanNotRemoveSelf),
    WrongDataInput: new BaseError('Office.WrongDataInput', OfficeErrorMessage.WrongDataInput),
    RTCErrorCannotMakeCallToYourself: new BaseError('Office.RTCErrorCannotMakeCallToYourself', OfficeErrorMessage.RTCErrorCannotMakeCallToYourself),
    RTCErrorRecipientInforNotFound: new BaseError('Office.RTCErrorRecipientInforNotFound', OfficeErrorMessage.RTCErrorRecipientInforNotFound),
    RTCErrorYouAreOnAnotherCall: new BaseError('Office.RTCErrorYouAreOnAnotherCall', OfficeErrorMessage.RTCErrorYouAreOnAnotherCall),
    RTCErrorCallInfoNotFound: new BaseError('Office.RTCErrotCallInfoNotFound', OfficeErrorMessage.RTCErrorCallInfoNotFound),
    RTCErrorTheCallHasEnded: new BaseError('Office.RTCErrorTheCallHasEnded', OfficeErrorMessage.RTCErrorTheCallHasEnded),
    RTCErrorUnableToConnectToUser: new BaseError('Office.RTCErrorUnableToConnectToUser', OfficeErrorMessage.RTCErrorUnableToConnectToUser),
    RTCErrorTheCallIsNotSharedWithYou: new BaseError('Office.RTCErrorTheCallIsNotSharedWithYou', OfficeErrorMessage.RTCErrorTheCallIsNotSharedWithYou),
    WrongDatePeriod: new BaseError('Office.WrongDatePeriod', OfficeErrorMessage.WrongDatePeriod),
    WrongEndDatePeriod: new BaseError('Office.WrongEndDatePeriod', OfficeErrorMessage.WrongEndDatePeriod),
    TaskNotExist: new BaseError('Office.TaskNotExist', OfficeErrorMessage.TaskNotExist),
    TaskNotAllowEditDoneTask: new BaseError('Office.TaskNotAllowEditDoneTask', OfficeErrorMessage.TaskNotAllowEditDoneTask),
    TaskNotAllowEditCancelTask: new BaseError('Office.TaskNotAllowEditCancelTask', OfficeErrorMessage.TaskNotAllowEditCancelTask),
    TaskUserNotHavePermission: new BaseError('Office.TaskUserNotHavePermission', OfficeErrorMessage.TaskUserNotHavePermission),
    TaskCommentNotOwnUser: new BaseError('Office.TaskCommentNotOwnUser', OfficeErrorMessage.TaskCommentNotOwnUser),
    LogCommentRequiredData: new BaseError('Office.LogCommentRequiredData', OfficeErrorMessage.LogCommentRequiredData),
    LogCommentAttachmentRequiredType: new BaseError('Office.LogCommentAttachmentRequiredType', OfficeErrorMessage.LogCommentAttachmentRequiredType),
    ChatSearchMessageConversationRequiredPartner: new BaseError('Office.ChatSearchMessageConversationRequiredPartner', OfficeErrorMessage.ChatSearchMessageConversationRequiredPartner),
    ChatSearchMessageGroupRequiredInfo: new BaseError('Office.ChatSearchMessageGroupRequiredInfo', OfficeErrorMessage.ChatSearchMessageGroupRequiredInfo),
    DoNotUpdateUserAtHere: new BaseError('Office.DoNotUpdateUserAtHere', OfficeErrorMessage.DoNotUpdateUserAtHere),
    WorkProfileInfoTypeError: new BaseError('Office.WorkProfileInfoTypeError', OfficeErrorMessage.WorkProfileInfoTypeError),
    WorkProfileInfoActionTypeCannotUpdate: new BaseError('Office.WorkProfileInfoActionTypeCannotUpdate', OfficeErrorMessage.WorkProfileInfoActionTypeCannotUpdate),
    ActiveDteOfUserWorkProfileMustUnique: new BaseError('Office.ActiveDteOfUserWorkProfileMustUnique', OfficeErrorMessage.ActiveDteOfUserWorkProfileMustUnique),
    WrongUserId: new BaseError('Office.WrongUserId', OfficeErrorMessage.WrongUserId),
    CampaignNeedReceiver: new BaseError('Office.CampaignNeedReceiver', OfficeErrorMessage.CampaignNeedReceiver),
    CampaignUserGetNotifyNotExist: new BaseError('Office.CampaignUserGetNotifyNotExist', OfficeErrorMessage.CampaignUserGetNotifyNotExist),
    CampaignPersonalRequireReceiver: new BaseError('Office.CampaignPersonalRequireReceiver', OfficeErrorMessage.CampaignPersonalRequireReceiver),
    ApprovalNeedUsed: new BaseError('Office.ApprovalNeedUsed', OfficeErrorMessage.ApprovalNeedUsed),
    AssetNotFound: new BaseError('Office.AssetNotFound', OfficeErrorMessage.AssetNotFound),
    AssetDataNotSameOrg: new BaseError('Office.AssetDataNotSameOrg', OfficeErrorMessage.AssetDataNotSameOrg),
    AssetOnlyOneManagementData: new BaseError('Office.AssetOnlyOneManagementData', OfficeErrorMessage.AssetOnlyOneManagementData),
    AssetOnlyOneAssignData: new BaseError('Office.AssetOnlyOneAssignData', OfficeErrorMessage.AssetOnlyOneAssignData),
    CategoryAssetNotFound: new BaseError('Office.CategoryAssetNotFound', OfficeErrorMessage.CategoryAssetNotFound),
    WarehouseAssetNotFound: new BaseError('Office.WarehouseAssetNotFound', OfficeErrorMessage.WarehouseAssetNotFound),
    CheckInBeaconNotFound: new BaseError('Office.CheckInBeaconNotFound', OfficeErrorMessage.CheckInBeaconNotFound),
    CheckInNeedPlaceNotFound: new BaseError('Office.CheckInNeedPlaceNotFound', OfficeErrorMessage.CheckInNeedPlaceNotFound),
    AssetNotHaveQuantity: new BaseError('Office.AssetNotHaveQuantity', OfficeErrorMessage.AssetNotHaveQuantity),
    ApprovalCanNotUpdate: new BaseError('Office.ApprovalCanNotUpdate', OfficeErrorMessage.ApprovalCanNotUpdate),
    ApprovalCanNotRemoveDefaultSubscriber: new BaseError('Office.ApprovalCanNotRemoveDefaultSubscriber', OfficeErrorMessage.ApprovalCanNotRemoveDefaultSubscriber),
    FilterNameExist: new BaseError('Office.FilterNameExist', OfficeErrorMessage.FilterNameExist),
    FilterNotFound: new BaseError('Office.FilterNotFound', OfficeErrorMessage.FilterNotFound),
    FilterUserApprovalNameExist: new BaseError('Office.FilterUserApprovalNameExist', OfficeErrorMessage.FilterUserApprovalNameExist),
    FilterUserApprovalNotFound: new BaseError('Office.FilterUserApprovalNotFound', OfficeErrorMessage.FilterUserApprovalNotFound),
    CloneConfigNotFound: new BaseError('Office.CloneConfigNotFound', OfficeErrorMessage.CloneConfigNotFound),
    CloneConfigByDateNeedEndOfSchedule: new BaseError('Office.CloneConfigByDateNeedEndOfSchedule', OfficeErrorMessage.CloneConfigByDateNeedEndOfSchedule),
    ApprovalFormGroupNotExist: new BaseError('Office.ApprovalFormGroupNotExist', OfficeErrorMessage.ApprovalFormGroupNotExist),
    ApprovalFormGroupNameExist: new BaseError('Office.ApprovalFormGroupNameExist', OfficeErrorMessage.ApprovalFormGroupNameExist),
    ApprovalFormGroupHaveFormCanNotRemove: new BaseError('Office.ApprovalFormGroupHaveFormCanNotRemove', OfficeErrorMessage.ApprovalFormGroupHaveFormCanNotRemove),
    DocumentWikiNotFound: new BaseError('Office.DocumentWikiNotFound', OfficeErrorMessage.DocumentWikiNotFound),
    DocumentWikiNameExisted: new BaseError('Office.DocumentWikiNameExisted', OfficeErrorMessage.DocumentWikiNameExisted),
    DocumentWikiCodeExisted: new BaseError('Office.DocumentWikiCodeExisted', OfficeErrorMessage.DocumentWikiCodeExisted),
    DocumentWikiCanNotCreateNewVer: new BaseError('Office.DocumentWikiCanNotCreateNewVer', OfficeErrorMessage.DocumentWikiCanNotCreateNewVer),
    DocumentWikiCannotRemove: new BaseError('Office.DocumentWikiCannotRemove', OfficeErrorMessage.DocumentWikiCannotRemove),
    NeedApproval: new BaseError('Office.NeedApproval', OfficeErrorMessage.NeedApproval),
    VersionWikiNotFound: new BaseError('Office.VersionWikiNotFound', OfficeErrorMessage.VersionWikiNotFound),
    VersionWikiUpdateNeedUpdateType: new BaseError('Office.VersionWikiUpdateNeedUpdateType', OfficeErrorMessage.VersionWikiUpdateNeedUpdateType),
    VersionWikiNotApprovalCannotRevert: new BaseError('Office.VersionWikiNotApprovalCannotRevert', OfficeErrorMessage.VersionWikiNotApprovalCannotRevert),
    CategoryWikiNotFound: new BaseError('Office.CategoryWikiNotFound', OfficeErrorMessage.CategoryWikiNotFound),
    CategoryWikiNameExist: new BaseError('Office.CategoryWikiNameExist', OfficeErrorMessage.CategoryWikiNameExist),
    CategoryWikiHaveWikiCanNotRemove: new BaseError('Office.CategoryWikiHaveWikiCanNotRemove', OfficeErrorMessage.CategoryWikiHaveWikiCanNotRemove),
    DeviceNotApprovedThisAccount: new BaseError('Office.DeviceNotApprovedThisAccount', OfficeErrorMessage.DeviceNotApprovedThisAccount),
    DeviceHasApproved: new BaseError('Office.DeviceNotApprovedThisAccount', OfficeErrorMessage.DeviceHasApproved),
    NotFoundDevice: new BaseError('Office.DeviceNotApprovedThisAccount', OfficeErrorMessage.NotFoundDevice),
    OrgChartNotAlowThisFeature: new BaseError('Office.OrgChartNotAlowThisFeature', OfficeErrorMessage.OrgChartNotAlowThisFeature),
    ApprovalForwardRequiredUser: new BaseError('Office.ApprovalForwardRequiredUser', OfficeErrorMessage.ApprovalForwardRequiredUser),
    TagDocumentNotFound: new BaseError('Office.TagDocumentNotFound', OfficeErrorMessage.TagDocumentNotFound),
    TagDocumentNameExist: new BaseError('Office.TagDocumentNameExist', OfficeErrorMessage.TagDocumentNameExist),
    TagDocumentHaveWikiCanNotRemove: new BaseError('Office.TagDocumentHaveWikiCanNotRemove', OfficeErrorMessage.TagDocumentHaveWikiCanNotRemove),
    LearningProjectCodeExisted: new BaseError('Office.LearningProjectCodeExisted', OfficeErrorMessage.LearningProjectCodeExisted),
    LearningProjectNameExisted: new BaseError('Office.LearningProjectNameExisted', OfficeErrorMessage.LearningProjectNameExisted),
    LearningProjectNotFound: new BaseError('Office.LearningProjectNotFound', OfficeErrorMessage.LearningProjectNotFound),
    LearningProjectHasStudent: new BaseError('Office.LearningProjectHasStudent', OfficeErrorMessage.LearningProjectHasStudent),
    LearningProjectStatusCannotUpdate: new BaseError('Office.LearningProjectStatusCannotUpdate', OfficeErrorMessage.LearningProjectStatusCannotUpdate),
    LearningProjectHaveActiveCourse: new BaseError('Office.LearningProjectHaveActiveCourse', OfficeErrorMessage.LearningProjectHaveActiveCourse),
    LearningProjectStatusCannotHide: new BaseError('Office.LearningProjectStatusCannotHide', OfficeErrorMessage.LearningProjectStatusCannotHide),
    LearningSkillNameExisted: new BaseError('Office.LearningSkillNameExisted', OfficeErrorMessage.LearningSkillNameExisted),
    LearningSkillNotFound: new BaseError('Office.LearningSkillNotFound', OfficeErrorMessage.LearningSkillNotFound),
    LearningCertificateNameExisted: new BaseError('Office.LearningCertificateNameExisted', OfficeErrorMessage.LearningCertificateNameExisted),
    LearningCertificateNotFound: new BaseError('Office.LearningCertificateNotFound', OfficeErrorMessage.LearningCertificateNotFound),
    LearningSectionNotFound: new BaseError('Office.LearningSectionNotFound', OfficeErrorMessage.LearningSectionNotFound),
    LearningLessonNotFound: new BaseError('Office.LearningLessonNotFound', OfficeErrorMessage.LearningLessonNotFound),
    LearningCourseNotFound: new BaseError('Office.LearningCourseNotFound', OfficeErrorMessage.LearningCourseNotFound),
    LearningCourseClosed: new BaseError('Office.LearningCourseClosed', OfficeErrorMessage.LearningCourseClosed),
    LearningCourseCodeExisted: new BaseError('Office.LearningCourseCodeExisted', OfficeErrorMessage.LearningCourseCodeExisted),
    LearningCourseNameExisted: new BaseError('Office.LearningCourseNameExisted', OfficeErrorMessage.LearningCourseNameExisted),
    LearningSectionNameExisted: new BaseError('Office.LearningSectionNameExisted', OfficeErrorMessage.LearningSectionNameExisted),
    LearningLessonNameExisted: new BaseError('Office.LearningLessonNameExisted', OfficeErrorMessage.LearningLessonNameExisted),
    LearningAddressNotFound:  new BaseError('Office.LearningAddressNotFound', OfficeErrorMessage.LearningAddressNotFound),
    LearningAddressNameExisted:  new BaseError('Office.LearningAddressNameExisted', OfficeErrorMessage.LearningAddressNameExisted),
}

